### ISSUE TITLE
 This branch is 6 commits ahead of main.

### ISSUE THREAD

**Issue by correabuscar** [pdoms/SHA256-PYTHON#1]
Hi. It seems that the `master` branch should be the default one, as it contains the fixes mentioned in the article like:

> Edit 13.02.2022: Urfasurfas pointed out that the preprocessMessage() function does not handle message lengths between 449 and 512bits, which has now been corrected.

But the `main` branch which is the current default, contains code from 2021 without the above fixes.

The line `Full code/git repo can be found here.` points to this repo which opens `main` branch by default.

<details>

My guess is that the `master` branch got renamed to `main` on the github webpage but not on the locally hosted repository and that the next push recreated the `master` branch ?
</details>

**Comment by pdoms** [comment]
@correabuscar thanks. Merged branches.
