### ISSUE TITLE
Q: Is it possible to backwards hash a reversed input from a given hash?

### ISSUE THREAD

**Issue by correabuscar** [pdoms/SHA256-PYTHON#2]
Hi. You wrote the sha256 implementation in this repository which makes me assume that you know how it works (unlike me, but I'm in the process of reading your article [here](https://medium.com/@domspaulo/python-implementation-of-sha-256-from-scratch-924f660c5d57)) and I was wondering if you could answer with YES or NO [this question](https://stackoverflow.com/q/73787368/19999437) which I'll reiterate here: 

Is possible to start from a given hash (which is the hash of an input string) and work backwards through the sha256 algorithm using the same input but in reverse order (from the last byte to the first) and get to the same initial hash (which is the hash of empty input, or a 0 bytes file) ?

For example:
I have the input `Hello World!` which (sha256)hashes to `7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069`
then can I use that very hash to go backwards via a reversed_sha256 algorithm(if it even can be reversed like that!) and coupled with the reversed input (`!dlroW olleH`) to get to the hash of the empty input which is `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` ?

Thank you in advance for any reply. It's much appreciated either way!
All the best to you!

**Comment by pdoms** [comment]
I'm not quite sure what you are trying to do with this procedure. In general, a hash should not be 'reversible', i.e., going from hash to input. As this is the reason this hash family is prefixed with 'secure' and is called a hash in general.

**Comment by correabuscar** [comment]
I agree, but I'm just trying to go back from current hash to previous hash, rather than the way the hash normally goes: forwards from previous hash to next hash by processing input. Though, perhaps what you're saying still applies to this too, ie. you can't go backwards in hashes even if you have the input string already.

Think of it like this:
```python
#!/usr/bin/python3
import hashlib
m4=hashlib.sha256()
print(m4.hexdigest()) # e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
#^ the hash of empty string or 0 bytes
m4.update(b"a")
print(m4.hexdigest()) # ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb
#^ the hash of string 'a'
m4.backwardsupdate(b"a")
print(m4.hexdigest()) # e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
#^ back to the hash of 0 bytes again
```
So, with the question from OP, I'm just trying to figure out if `backwardsupdate` is implementable.

*EDIT:* I shall get back to reading your article, as I've postponed it, and thus I should be able to answer this question myself, presumably, soon.

**Comment by correabuscar** [comment]
There's some bit lossiness(due to bit shifting and AND-ing with a bit mask) that tells me I can't go backwards. But I still haven't looked deep enough to get it.

**Comment by pdoms** [comment]
Hey, sorry for the late reply, was quite busy the last days. As you described the backwards process, it seems more like an issue of saving the previous hash in some way or the other. Like I said, going backwards from any given hash to an unknown input is nearly impossible with the SHA2 family. There are other non-crypto algorithms that should be able to do that. If you don't mind me asking, why do you need to reverse?

**Comment by correabuscar** [comment]
> Hey, sorry for the late reply, was quite busy the last days. As you described the backwards process, it seems more like an issue of saving the previous hash in some way or the other. Like I said, going backwards from any given hash to an unknown input is nearly impossible with the SHA2 family. There are other non-crypto algorithms that should be able to do that. If you don't mind me asking, why do you need to reverse?

No worries. Note: that the input and its size is known, it's just that it's in reverse bytes order.

I wanted to check if the second half of a singly-linked list is the reverse of the first half, in O(1) space complexity, ie. palindrome test. I mentioned it here: https://stackoverflow.com/q/73787368/19999437

**Comment by pdoms** [comment]
Got it, in that case: forget about the SHA256 - look into a hash algorithm that is used, e.g., for hashmaps, or maybe a checksum (crc32), but sufficient enough to avoid a lot of collisions.

**Comment by correabuscar** [comment]
Thanks!
Looks like experts are using something called polyhash for exactly this thing: palindromes. I haven't looked into it yet though.

https://baites.github.io/algorithms/algorithm-analysis/2020/03/23/string-hashing-and-palindromes.html
https://ideone.com/6BWI94

**Comment by pdoms** [comment]
That is more or less what i was thinking of too.But haven't looked into it thoroughly as well.
